all:
	gcc -Wall -o ej01 ej01.c
	gcc -Wall -o ej01_1 ej01_1.c
	gcc -Wall -o ej02 ej02.c
	gcc -Wall -o ej02_1 ej02_1.c
	gcc -Wall -o fifo fifo.c
	gcc -Wall -o lifo lifo.c

clean:
	rm -f ./ej01
	rm -f ./ej01_1
	rm -f ./ej02
	rm -f ./ej02_1
	rm -f fifo
	rm -f lifo
	rm -f *~


