compileall:
	gcc -Wall -o ejem8_1 ejem8_1.c
	gcc -Wall -o ejem8_2 ejem8_2.c
	gcc -Wall -o ejem9_1 ejem9_1.c
	gcc -Wall -o ejem9_2 ejem9_2.c
	gcc -Wall -o ejem10 ejem10.c
	gcc -Wall -o ejem11 ejem11.c

clean:
	rm -f ejem8_1
	rm -f ejem8_2
	rm -f ejem9_1
	rm -f ejem9_2
	rm -f ejem10
	rm -f ejem11

all: clean compileall
